[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/app.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"

[[headers]]
  for = "/words.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"

[[headers]]
  for = "/extraWords.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"
