import { EXTRA_WORDS } from "./extraWords.js";

export const WORDS = {
  easy: [
    "CAT","DOG","FISH","BIRD","BEAR","LION","FROG","DUCK","COW","PIG","BEE","ANT",
    "WOLF","DEER","CRAB","SHARK","EAGLE","WHALE","HORSE","SNAKE","TURTLE","RABBIT",
    "ELEPHANT","GIRAFFE","PENGUIN","DOLPHIN","BUTTERFLY","CHICKEN","MONKEY","TIGER",
    "PIZZA","CAKE","BREAD","APPLE","MILK","EGG","RICE","SOUP","SALT","SUGAR",
    "CHEESE","PASTA","BUTTER","HONEY","LEMON","ORANGE","GRAPE","BERRY","MANGO",
    "COOKIE","SANDWICH","CHOCOLATE","COFFEE","TEA","JUICE","WATER","BANANA","TOMATO",
    "BALL","BOOK","DOOR","CHAIR","TABLE","CLOCK","PHONE","LAMP","CUP","BOX",
    "KEY","KNIFE","FORK","SPOON","BOWL","BAG","HAT","SHOE","RING","COIN",
    "MIRROR","PILLOW","BLANKET","WINDOW","CANDLE","PENCIL","HAMMER","WHEEL","ROPE","CAMERA",
    "BEACH","PARK","SCHOOL","STORE","FARM","CASTLE","CAVE","FOREST","ISLAND","RIVER",
    "LAKE","MOUNTAIN","DESERT","JUNGLE","CITY","TOWN","BRIDGE","CHURCH","GARDEN","ZOO",
    "JUMP","RUN","SWIM","SLEEP","DREAM","SMILE","LAUGH","CRY","DANCE","SING",
    "FIRE","RAIN","SNOW","WIND","STORM","STAR","MOON","SUN","CLOUD","NIGHT"
  ],
  medium: [
    "OCTOPUS","FLAMINGO","CROCODILE","PARROT","HAMSTER","CHEETAH","GORILLA","PANDA",
    "HEDGEHOG","PLATYPUS","JAGUAR","PEACOCK","OSTRICH","LOBSTER","SEAHORSE",
    "SUSHI","TACOS","BAGEL","WAFFLE","BURRITO","DUMPLING","PRETZEL","MUFFIN",
    "AVOCADO","BROCCOLI","MUSHROOM","PINEAPPLE","COCONUT","POPCORN","CARAMEL",
    "ESPRESSO","SMOOTHIE","LASAGNA","OMELETTE","KEBAB","PANCAKE","CROISSANT",
    "COMPASS","TELESCOPE","LANTERN","ANCHOR","TROPHY","UMBRELLA","PUZZLE","MAGNET",
    "SYRINGE","THERMOMETER","CALCULATOR","HEADPHONES","KEYBOARD","SCISSORS","CANTEEN",
    "BRIEFCASE","CALENDAR","NOTEBOOK","ENVELOPE","STAPLER","FLASHLIGHT","BINOCULARS",
    "VOLCANO","GLACIER","CANYON","LIGHTHOUSE","PYRAMID","STADIUM","MUSEUM","AIRPORT",
    "HARBOUR","MEADOW","SWAMP","VALLEY","CLIFF","WATERFALL","GREENHOUSE","CEMETERY",
    "SHADOW","ECHO","MIRAGE","LEGEND","MYSTERY","PARADE","CARNIVAL","ADVENTURE",
    "VOYAGE","RESCUE","TREASURE","SECRET","RIDDLE","MAGIC","CURSE","GRAVITY",
    "ECLIPSE","AURORA","TORNADO","TSUNAMI","AVALANCHE","DROUGHT","MONSOON",
    "JEALOUSY","NOSTALGIA","CURIOSITY","BOREDOM","ANXIETY","COURAGE","PATIENCE",
    "GUILT","PRIDE","ENVY","REGRET","WONDER","FURY","BLISS","DREAD"
  ],
  hard: [
    "IRONY","KARMA","CHAOS","FATE","PARADOX","EUPHORIA","SOLITUDE","SERENITY",
    "AUDACITY","ENTROPY","LEGACY","MOMENTUM","CATALYST","RESONANCE","THRESHOLD",
    "SYMMETRY","HIERARCHY","SPECTRUM","PARADIGM","SYNTHESIS","ATROPHY","LETHARGY",
    "ELOQUENCE","SUBTLETY","AMBIGUITY","SYNCHRONY","DISSONANCE","CONVERGENCE",
    "SEXTANT","ABACUS","MONOCLE","PERISCOPE","TREBUCHET","ASTROLABE","SCALPEL",
    "GUILLOTINE","PENDULUM","CAULDRON","BELLOWS","GALLOWS","CATAPULT","SICKLE","ANVIL",
    "TECTONIC","SOLSTICE","EQUINOX","PHOTON","QUASAR","NEBULA","MAGNETAR",
    "SYMBIOSIS","OSMOSIS","MITOSIS","TAXONOMY","ISOTOPE","POLYMER","ELECTRODE",
    "CHROMOSOME","STALACTITE","PERMAFROST","BIOLUMINESCENCE","METAMORPHOSIS",
    "OLIGARCHY","RENAISSANCE","PROPAGANDA","COLONIALISM","BUREAUCRACY","ANARCHY",
    "MERCENARY","HEGEMONY","DYSTOPIA","UTOPIA","SCHISM","DIASPORA","MANIFESTO",
    "FRESCO","MOSAIC","GARGOYLE","BUTTRESS","ROTUNDA","BASILICA","MAUSOLEUM",
    "OBELISK","COLONNADE","LABYRINTH","AQUEDUCT","AMPHITHEATRE","CATACOMBS"
  ]
};

export const ALL_WORDS = [...new Set([...WORDS.easy, ...WORDS.medium, ...WORDS.hard, ...EXTRA_WORDS])];

export function getWordList(count = 10) {
  const pool = [...ALL_WORDS];
  for (let index = pool.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(Math.random() * (index + 1));
    [pool[index], pool[swapIndex]] = [pool[swapIndex], pool[index]];
  }
  return pool.slice(0, count);
}
