// Short meanings for secret words — helps players who don't know the word. Not for use as clues.

export const WORD_MEANINGS = {
  CAT: "a furry pet that meows",
  DOG: "a pet that barks",
  FISH: "lives in water, has fins",
  BIRD: "has feathers and flies",
  BEAR: "large furry wild animal",
  LION: "big cat, king of the jungle",
  FROG: "jumps and lives near water",
  DUCK: "water bird with a flat bill",
  COW: "farm animal that gives milk",
  PIG: "farm animal that oinks",
  BEE: "insect that makes honey",
  ANT: "tiny insect that lives in colonies",
  WOLF: "wild dog that howls",
  DEER: "animal with antlers",
  CRAB: "sea creature with pincers",
  SHARK: "large ocean predator",
  EAGLE: "large bird of prey",
  WHALE: "huge ocean mammal",
  HORSE: "animal you can ride",
  SNAKE: "legless reptile that slithers",
  TURTLE: "reptile with a shell",
  RABBIT: "small animal with long ears",
  ELEPHANT: "huge animal with a trunk",
  GIRAFFE: "tall animal with a long neck",
  PENGUIN: "black-and-white flightless bird",
  DOLPHIN: "smart ocean mammal",
  BUTTERFLY: "insect with colorful wings",
  CHICKEN: "farm bird that lays eggs",
  MONKEY: "primate that swings in trees",
  TIGER: "big striped cat",
  PIZZA: "flat baked dish with toppings",
  CAKE: "sweet baked dessert",
  BREAD: "baked food made from flour",
  APPLE: "round fruit, red or green",
  MILK: "white drink from cows",
  EGG: "oval food from chickens",
  RICE: "white grains you cook",
  SOUP: "liquid food in a bowl",
  SALT: "white seasoning, makes food salty",
  SUGAR: "sweet crystals for food",
  CHEESE: "dairy product from milk",
  PASTA: "Italian noodles",
  BUTTER: "yellow spread from cream",
  HONEY: "sweet substance from bees",
  LEMON: "sour yellow citrus fruit",
  ORANGE: "round orange citrus fruit",
  GRAPE: "small fruit that grows in bunches",
  BERRY: "small round fruit",
  MANGO: "tropical sweet fruit",
  COOKIE: "small sweet baked treat",
  SANDWICH: "food between two slices of bread",
  CHOCOLATE: "sweet brown treat",
  COFFEE: "hot drink made from beans",
  TEA: "hot drink from leaves",
  JUICE: "drink from squeezed fruit",
  WATER: "clear liquid you drink",
  BANANA: "long yellow fruit",
  TOMATO: "red fruit used in salads",
  BALL: "round object you throw or kick",
  BOOK: "pages with writing, you read it",
  DOOR: "opens to enter a room",
  CHAIR: "you sit on it",
  TABLE: "furniture with a flat top",
  CLOCK: "shows the time",
  PHONE: "device for calling",
  LAMP: "gives light",
  CUP: "you drink from it",
  BOX: "container with sides",
  KEY: "opens locks",
  KNIFE: "sharp tool for cutting",
  FORK: "eating utensil with prongs",
  SPOON: "eating utensil for soup",
  BOWL: "round dish for food",
  BAG: "you carry things in it",
  HAT: "worn on your head",
  SHOE: "worn on your feet",
  RING: "worn on finger",
  COIN: "metal money",
  MIRROR: "reflective glass",
  PILLOW: "you rest your head on it",
  BLANKET: "keeps you warm in bed",
  WINDOW: "glass opening in a wall",
  CANDLE: "wax with a wick that burns",
  PENCIL: "writing tool with lead",
  HAMMER: "tool for hitting nails",
  WHEEL: "round part that rolls",
  ROPE: "thick cord",
  CAMERA: "takes photos",
  BEACH: "sandy place by the ocean",
  PARK: "green space with trees",
  SCHOOL: "place where you learn",
  STORE: "place where you buy things",
  FARM: "where crops and animals are raised",
  CASTLE: "large old stone building",
  CAVE: "hole in a mountain or ground",
  FOREST: "place with many trees",
  ISLAND: "land surrounded by water",
  RIVER: "flowing body of water",
  LAKE: "body of water surrounded by land",
  MOUNTAIN: "very tall natural elevation",
  DESERT: "dry sandy place",
  JUNGLE: "tropical forest",
  CITY: "large populated place",
  TOWN: "smaller than a city",
  BRIDGE: "crosses over water or a road",
  CHURCH: "place of worship",
  GARDEN: "place where plants grow",
  ZOO: "where animals are kept to see",
  JUMP: "leave the ground with your feet",
  RUN: "move fast on foot",
  SWIM: "move through water",
  SLEEP: "rest with your eyes closed",
  DREAM: "images while you sleep",
  SMILE: "happy face expression",
  LAUGH: "sound when something is funny",
  CRY: "tears from your eyes",
  DANCE: "move to music",
  SING: "make music with your voice",
  FIRE: "flames and heat",
  RAIN: "water falling from clouds",
  SNOW: "white frozen precipitation",
  WIND: "moving air",
  STORM: "bad weather with rain or snow",
  STAR: "bright point in the night sky",
  MOON: "in the sky at night",
  SUN: "bright star that gives daylight",
  CLOUD: "white or gray in the sky",
  NIGHT: "when it's dark outside",
  OCTOPUS: "sea animal with eight arms",
  FLAMINGO: "pink bird that stands on one leg",
  CROCODILE: "reptile with a long snout",
  PARROT: "colorful bird that can talk",
  HAMSTER: "small furry pet in a wheel",
  CHEETAH: "fastest land animal",
  GORILLA: "large ape",
  PANDA: "black-and-white bear from China",
  HEDGEHOG: "small animal with spines",
  PLATYPUS: "egg-laying mammal with a bill",
  JAGUAR: "big spotted cat",
  PEACOCK: "bird with fancy tail feathers",
  OSTRICH: "large bird that can't fly",
  LOBSTER: "sea creature with claws",
  SEAHORSE: "small fish with a horse-like head",
  SUSHI: "Japanese rice and fish dish",
  TACOS: "Mexican food in a tortilla",
  BAGEL: "ring-shaped bread",
  WAFFLE: "breakfast food with squares",
  BURRITO: "wrap with filling",
  DUMPLING: "small filled dough",
  PRETZEL: "twisted salty snack",
  MUFFIN: "small sweet cake",
  AVOCADO: "green fruit with a pit",
  BROCCOLI: "green vegetable with florets",
  MUSHROOM: "fungus you can eat",
  PINEAPPLE: "spiky tropical fruit",
  COCONUT: "hard tropical nut with milk",
  POPCORN: "popped corn kernels",
  CARAMEL: "sweet brown sauce",
  ESPRESSO: "strong Italian coffee",
  SMOOTHIE: "blended fruit drink",
  LASAGNA: "layered pasta dish",
  OMELETTE: "folded egg dish",
  KEBAB: "meat on a stick",
  PANCAKE: "flat round breakfast food",
  CROISSANT: "flaky French pastry",
  COMPASS: "shows direction",
  TELESCOPE: "for looking at stars",
  LANTERN: "portable light",
  ANCHOR: "keeps a boat in place",
  TROPHY: "award you win",
  UMBRELLA: "keeps rain off you",
  PUZZLE: "game with pieces to fit",
  MAGNET: "attracts metal",
  VOLCANO: "mountain that can erupt",
  GLACIER: "slow-moving ice",
  CANYON: "deep valley with steep sides",
  LIGHTHOUSE: "tower with a light for ships",
  PYRAMID: "triangle-shaped ancient building",
  STADIUM: "place for sports events",
  MUSEUM: "place for art and history",
  AIRPORT: "where planes take off",
  HARBOUR: "where boats dock",
  MEADOW: "field of grass and flowers",
  SWAMP: "wet muddy land",
  VALLEY: "low land between hills",
  CLIFF: "steep rock face",
  WATERFALL: "water falling from a height",
  ECLIPSE: "when sun or moon is hidden",
  AURORA: "northern lights in the sky",
  TORNADO: "spinning funnel of wind",
  TSUNAMI: "huge ocean wave",
  AVALANCHE: "snow sliding down a mountain",
  DROUGHT: "long period without rain",
  MONSOON: "seasonal heavy rain",
  SECRET: "something hidden or private",
  RIDDLE: "puzzle question",
  MAGIC: "tricks or supernatural power",
  TREASURE: "valuable hidden thing",
  VOYAGE: "long journey",
  RESCUE: "save someone from danger",
  ADVENTURE: "exciting journey",
  MYSTERY: "something unknown",
  LEGEND: "famous old story",
  ECHO: "sound that bounces back",
  SHADOW: "dark shape when light is blocked",
  GRAVITY: "force that pulls things down",
  CURSE: "bad wish or spell",
  JEALOUSY: "envy of someone else",
  NOSTALGIA: "missing the past",
  CURIOSITY: "wanting to know more",
  BOREDOM: "having nothing to do",
  ANXIETY: "worry or nervousness",
  COURAGE: "bravery",
  PATIENCE: "waiting calmly",
  GUILT: "feeling you did wrong",
  PRIDE: "feeling good about yourself",
  ENVY: "wanting what others have",
  REGRET: "wish you hadn't done something",
  WONDER: "amazement or curiosity",
  FURY: "extreme anger",
  BLISS: "perfect happiness",
  DREAD: "fear of something bad",
  IRONY: "when the opposite of expected happens",
  KARMA: "what you do comes back",
  CHAOS: "total disorder",
  FATE: "destiny",
  PARADOX: "contradiction that might be true",
  EUPHORIA: "intense happiness",
  SOLITUDE: "being alone",
  SERENITY: "peace and calm",
  JANUARY: "first month of the year",
  FEBRUARY: "second month",
  MARCH: "third month",
  APRIL: "fourth month",
  MAY: "fifth month",
  JUNE: "sixth month",
  JULY: "seventh month",
  AUGUST: "eighth month",
  SEPTEMBER: "ninth month",
  OCTOBER: "tenth month",
  NOVEMBER: "eleventh month",
  DECEMBER: "twelfth month",
  HOME: "where you live",
  GAME: "something you play",
  MUSIC: "sounds and songs",
  MOVIE: "film you watch",
  FRIEND: "person you like",
  FAMILY: "parents, siblings, etc.",
  LOVE: "deep affection",
  PARTY: "celebration with people",
  TRAVEL: "going to other places",
  SUMMER: "hot season",
  WINTER: "cold season",
  SPRING: "season when flowers bloom",
  FALL: "season when leaves drop"
};

export function getWordMeaning(word) {
  if (!word || word === "---") return null;
  const key = String(word).trim().toUpperCase();
  return WORD_MEANINGS[key] || null;
}
